<!--
Codes Generated By VForm:
http://vue.devtools.com
-->
<template>
  <el-form :model="formData" ref="vForm" :rules="rules" label-position="left" label-width="300px"
    size="default" @submit.prevent>
    <div class="static-content-item">
      <div>Renew form</div>
    </div>
    <div class="static-content-item">
      <el-divider direction="horizontal"></el-divider>
    </div>
    <el-row>
      <el-col :span="24" class="grid-cell">
        <el-form-item label=" Name as in Passport MRZ format:" prop="input12931"
          class="required label-right-align">
          <el-input v-model="formData.input12931" type="text" clearable></el-input>
        </el-form-item>
        <el-form-item label="Matric Number:" prop="input69350" class="required label-right-align">
          <el-input v-model="formData.input69350" type="text" clearable></el-input>
        </el-form-item>
        <el-form-item label="Passport Number:" prop="input23031" class="required label-right-align">
          <el-input v-model="formData.input23031" type="text" clearable></el-input>
        </el-form-item>
        <el-form-item label="Email Address:" prop="input96155" class="required label-right-align">
          <el-input v-model="formData.input96155" type="text" clearable></el-input>
        </el-form-item>
      </el-col>
    </el-row>
    <el-row>
      <el-col :span="24" class="grid-cell">
        <div class="static-content-item">
          <el-divider direction="horizontal"></el-divider>
        </div>
        <el-form-item label=" Full Address in Malaysia:" prop="textarea21654"
          class="required label-right-align">
          <el-input type="textarea" v-model="formData.textarea21654" rows="3"></el-input>
        </el-form-item>
      </el-col>
      <el-col :span="24" class="grid-cell">
        <el-form-item label=" Full Address  Overseas:" prop="textarea105654"
          class="required label-right-align">
          <el-input type="textarea" v-model="formData.textarea105654" rows="3"></el-input>
        </el-form-item>
      </el-col>
    </el-row>
    <div class="static-content-item">
      <el-divider direction="horizontal"></el-divider>
    </div>
    <el-row>
      <el-col :span="24" class="grid-cell">
        <el-form-item label=" Course Level:" prop="radio80337" class="required label-center-align">
          <el-radio-group v-model="formData.radio80337">
            <el-radio v-for="(item, index) in radio80337Options" :key="index" :label="item.value"
              :disabled="item.disabled" style="{display: inline}">{{item.label}}</el-radio>
          </el-radio-group>
        </el-form-item>
      </el-col>
    </el-row>
    <div class="static-content-item">
      <el-divider direction="horizontal"></el-divider>
    </div>
    <el-row>
      <el-col :span="24" class="grid-cell">
        <el-form-item label="Nationality:" prop="input113152" class="required label-right-align">
          <el-input v-model="formData.input113152" type="text" clearable></el-input>
        </el-form-item>
        <el-form-item label="Mobile Number: (WhatsApp)" prop="input40240" class="required label-right-align">
          <el-input v-model="formData.input40240" type="text" clearable></el-input>
        </el-form-item>
      </el-col>
    </el-row>
    <el-row>
      <el-col :span="24" class="grid-cell">
        <div class="static-content-item">
          <el-divider direction="horizontal"></el-divider>
        </div>
        <el-form-item label="Location when applying:" prop="radio48252" class="required">
          <el-radio-group v-model="formData.radio48252">
            <el-radio v-for="(item, index) in radio48252Options" :key="index" :label="item.value"
              :disabled="item.disabled" style="{display: inline}">{{item.label}}</el-radio>
          </el-radio-group>
        </el-form-item>
        <div class="static-content-item">
          <el-divider direction="horizontal"></el-divider>
        </div>
      </el-col>
      <el-col :span="24" class="grid-cell">
        <el-form-item label="Course Name:" prop="input78584" class="required label-right-align">
          <el-input v-model="formData.input78584" type="text"
            placeholder="Example : Bachelor of Science , Master of Science, Doctor of Philosophy / Engineering"
            clearable></el-input>
        </el-form-item>
        <div class="static-content-item">
          <el-divider direction="horizontal"></el-divider>
        </div>
        <el-form-item label="Faculty's / Institute's /  School's Name:" prop="input32153"
          class="required label-right-align">
          <el-input v-model="formData.input32153" type="text" placeholder="Example : Faculty of Agriculture"
            clearable></el-input>
        </el-form-item>
        <div class="static-content-item">
          <el-divider direction="horizontal"></el-divider>
        </div>
        <el-form-item label="Supervisor's / Advisor's Name:" prop="input82694"
          class="required label-right-align">
          <el-input v-model="formData.input82694" type="text" clearable></el-input>
        </el-form-item>
        <div class="static-content-item">
          <el-divider direction="horizontal"></el-divider>
        </div>
      </el-col>
    </el-row>
    <div class="static-content-item">
      <el-divider direction="horizontal"></el-divider>
    </div>
    <el-row>
      <el-col :span="24" class="grid-cell">
        <el-form-item label="Sponsorship status:" prop="radio15322" class="label-right-align">
          <el-radio-group v-model="formData.radio15322">
            <el-radio v-for="(item, index) in radio15322Options" :key="index" :label="item.value"
              :disabled="item.disabled" style="{display: inline}">{{item.label}}</el-radio>
          </el-radio-group>
        </el-form-item>
        <el-form-item label="Study Status: (Current semester)" prop="select30151"
          class="required label-right-align">
          <el-select v-model="formData.select30151" class="full-width-input" clearable>
            <el-option v-for="(item, index) in select30151Options" :key="index" :label="item.label"
              :value="item.value" :disabled="item.disabled"></el-option>
          </el-select>
        </el-form-item>
        <el-form-item label="Marital Status:" prop="radio7296" class="required label-right-align">
          <el-radio-group v-model="formData.radio7296">
            <el-radio v-for="(item, index) in radio7296Options" :key="index" :label="item.value"
              :disabled="item.disabled" style="{display: inline}">{{item.label}}</el-radio>
          </el-radio-group>
        </el-form-item>
        <div class="static-content-item">
          <el-divider direction="horizontal"></el-divider>
        </div>
        <el-form-item label="Date of Birth:" prop="date23034" class="required label-right-align">
          <el-date-picker v-model="formData.date23034" type="date" class="full-width-input"
            format="YYYY-MM-DD" value-format="YYYY-MM-DD" clearable></el-date-picker>
        </el-form-item>
        <div class="static-content-item">
          <el-divider direction="horizontal"></el-divider>
        </div>
        <el-form-item label="Validity Date of Current Pass:" prop="date101014"
          class="required label-right-align">
          <el-date-picker v-model="formData.date101014" type="date" class="full-width-input"
            format="YYYY-MM-DD" value-format="YYYY-MM-DD" clearable></el-date-picker>
        </el-form-item>
        <div class="static-content-item">
          <el-divider direction="horizontal"></el-divider>
        </div>
        <el-form-item label="Travel Document Issued Date:" prop="date36546"
          class="required label-right-align">
          <el-date-picker v-model="formData.date36546" type="date" class="full-width-input"
            format="YYYY-MM-DD" value-format="YYYY-MM-DD" clearable></el-date-picker>
        </el-form-item>
        <div class="static-content-item">
          <el-divider direction="horizontal"></el-divider>
        </div>
        <el-form-item label="Travel Document Valid Until:" prop="date65368"
          class="required label-right-align">
          <el-date-picker v-model="formData.date65368" type="date" class="full-width-input"
            format="YYYY-MM-DD" value-format="YYYY-MM-DD" clearable></el-date-picker>
        </el-form-item>
        <div class="static-content-item">
          <el-divider direction="horizontal"></el-divider>
        </div>
        <el-form-item label="Latest date enter Malaysia:" prop="date35169" class="required label-right-align">
          <el-date-picker v-model="formData.date35169" type="date" class="full-width-input"
            format="YYYY-MM-DD" value-format="YYYY-MM-DD" clearable></el-date-picker>
        </el-form-item>
        <div class="static-content-item">
          <el-divider direction="horizontal"></el-divider>
        </div>
        <el-form-item label="Travel Document (Passport) Type:" prop="radio37785"
          class="required label-right-align">
          <el-radio-group v-model="formData.radio37785">
            <el-radio v-for="(item, index) in radio37785Options" :key="index" :label="item.value"
              :disabled="item.disabled" style="{display: inline}">{{item.label}}</el-radio>
          </el-radio-group>
        </el-form-item>
        <el-form-item label="Type of Current Pass:" prop="select66842" class="required label-right-align">
          <el-select v-model="formData.select66842" class="full-width-input" clearable>
            <el-option v-for="(item, index) in select66842Options" :key="index" :label="item.label"
              :value="item.value" :disabled="item.disabled"></el-option>
          </el-select>
        </el-form-item>
      </el-col>
    </el-row>
    <div class="static-content-item">
      <el-divider direction="horizontal"></el-divider>
    </div>
    <el-row>
      <el-col :span="24" class="grid-cell">
        <el-form-item label="Boarding Pass" prop="fileupload21603" class="label-right-align">
          <el-upload :file-list="fileupload21603FileList" :headers="fileupload21603UploadHeaders"
            :data="fileupload21603UploadData" :action="'http://localhost:8080/apply/uploadFile21603'" list-type="picture-card" show-file-list :limit="1"><template
              #tip>
              <div class="el-upload__tip">Boarding Pass (If Use Auto Gate)</div>
            </template> <template #default><i class="el-icon-plus"></i></template></el-upload>
        </el-form-item>
      </el-col>
      <el-col :span="24" class="grid-cell">
        <el-form-item label="Passport" prop="fileupload21116" class="required label-right-align">
          <el-upload :file-list="fileupload21116FileList" :headers="fileupload21116UploadHeaders"
            :data="fileupload21116UploadData" :action="'http://localhost:8080/apply/uploadFile21116'" list-type="picture-card" show-file-list :limit="1"><template
              #tip>
              <div class="el-upload__tip">Current Passport Pages (All pages)</div>
            </template> <template #default><i class="el-icon-plus"></i></template></el-upload>
        </el-form-item>
      </el-col>
      <el-col :span="24" class="grid-cell">
        <el-form-item label="Old Passport" prop="fileupload64222" class="label-right-align">
          <el-upload :file-list="fileupload64222FileList" :headers="fileupload64222UploadHeaders"
            :data="fileupload64222UploadData" list-type="picture-card" show-file-list :limit="1"><template
              #tip>
              <div class="el-upload__tip">Old Passport Pages (If have)</div>
            </template> <template #default><i class="el-icon-plus"></i></template></el-upload>
        </el-form-item>
      </el-col>
      <el-col :span="24" class="grid-cell">
        <el-form-item label="Registration Slip" prop="fileupload95845" class="label-right-align">
          <el-upload :file-list="fileupload95845FileList" :headers="fileupload95845UploadHeaders"
            :data="fileupload95845UploadData" list-type="picture-card" show-file-list :limit="5"><template
              #tip>
              <div class="el-upload__tip">Latest Registration Slip</div>
            </template> <template #default><i class="el-icon-plus"></i></template></el-upload>
        </el-form-item>
      </el-col>
      <el-col :span="24" class="grid-cell">
        <el-form-item label="Academic Result" prop="fileupload93148" class="label-right-align">
          <el-upload :file-list="fileupload93148FileList" :headers="fileupload93148UploadHeaders"
            :data="fileupload93148UploadData" list-type="picture-card" show-file-list :limit="5"> <template
              #default><i class="el-icon-plus"></i></template></el-upload>
        </el-form-item>
      </el-col>
      <el-col :span="24" class="grid-cell">
        <el-form-item label="Attendance Report" prop="fileupload45459" class="label-right-align">
          <el-upload :file-list="fileupload45459FileList" :headers="fileupload45459UploadHeaders"
            :data="fileupload45459UploadData" list-type="picture-card" show-file-list :limit="5"> <template
              #default><i class="el-icon-plus"></i></template></el-upload>
        </el-form-item>
      </el-col>
      <el-col :span="24" class="grid-cell">
        <el-form-item label="Progress Report" prop="fileupload97014" class="label-right-align">
          <el-upload :file-list="fileupload97014FileList" :headers="fileupload97014UploadHeaders"
            :data="fileupload97014UploadData" list-type="picture-card" show-file-list :limit="3"> <template
              #default><i class="el-icon-plus"></i></template></el-upload>
        </el-form-item>
      </el-col>
      <el-col :span="24" class="grid-cell">
        <el-form-item label="Supporting Letter" prop="fileupload95564" class="label-right-align">
          <el-upload :file-list="fileupload95564FileList" :headers="fileupload95564UploadHeaders"
            :data="fileupload95564UploadData" list-type="picture-card" show-file-list :limit="3"> <template
              #default><i class="el-icon-plus"></i></template></el-upload>
        </el-form-item>
      </el-col>
      <el-col :span="24" class="grid-cell">
        <el-form-item label="EMGS Payment" prop="fileupload8438" class="label-right-align">
          <el-upload :file-list="fileupload8438FileList" :headers="fileupload8438UploadHeaders"
            :data="fileupload8438UploadData" list-type="picture-card" show-file-list :limit="3"><template
              #tip>
              <div class="el-upload__tip">Proof of EMGS Payment</div>
            </template> <template #default><i class="el-icon-plus"></i></template></el-upload>
        </el-form-item>
      </el-col>
      <el-col :span="24" class="grid-cell">
        <el-form-item label="UPM Payment" prop="fileupload59826" class="label-right-align">
          <el-upload :file-list="fileupload59826FileList" :headers="fileupload59826UploadHeaders"
            :data="fileupload59826UploadData" list-type="picture-card" show-file-list :limit="3"><template
              #tip>
              <div class="el-upload__tip">Proof of UPM Payment</div>
            </template> <template #default><i class="el-icon-plus"></i></template></el-upload>
        </el-form-item>
        <div class="static-content-item">
          <el-divider direction="horizontal"></el-divider>
        </div>
      </el-col>
      <el-col :span="24" class="grid-cell">
        <el-form-item label=" Insurance Cover Note Company:" prop="input50733" class="label-right-align">
          <el-input v-model="formData.input50733" type="text" placeholder="Example :  AIA" clearable>
          </el-input>
        </el-form-item>
        <div class="static-content-item">
          <el-divider direction="horizontal"></el-divider>
        </div>
      </el-col>
      <el-col :span="24" class="grid-cell">
        <el-form-item label="Insurance Cover Note" prop="fileupload59469" class="label-right-align">
          <el-upload :file-list="fileupload59469FileList" :headers="fileupload59469UploadHeaders"
            :data="fileupload59469UploadData" list-type="picture-card" show-file-list :limit="3"> <template
              #default><i class="el-icon-plus"></i></template></el-upload>
        </el-form-item>
      </el-col>
    </el-row>
    <div class="static-content-item">
      <el-divider direction="horizontal"></el-divider>
    </div>
    <el-row>
      <el-col :span="12" class="grid-cell">
        <div class="static-content-item">
          <el-button type="primary">SAVE</el-button>
        </div>
      </el-col>
      <el-col :span="12" class="grid-cell">
        <div class="static-content-item">
          <el-button type="primary" @click="submitForm">SUBMIT</el-button>
        </div>
      </el-col>
    </el-row>
    <el-row>
      <el-col :span="24" class="grid-cell">
      </el-col>
      <el-col :span="24" class="grid-cell">
      </el-col>
    </el-row>
    <div class="static-content-item">
      <el-divider direction="horizontal"></el-divider>
    </div>
    <div class="static-content-item">
      <el-divider direction="horizontal"></el-divider>
    </div>
    <div class="static-content-item">
      <el-divider direction="horizontal"></el-divider>
    </div>
  </el-form>
  
</template>

<script>

import axios from 'axios';
import { ElMessageBox } from 'element-plus';
  import {
    defineComponent,
    toRefs,
    reactive,
    getCurrentInstance
  }
  from 'vue'
  export default defineComponent({
    components: {},
    props: {},
    setup() {
      const state = reactive({
        formData: {
          input12931: "",
          input69350: "",
          input23031: "",
          input96155: "",
          textarea21654: "",
          textarea105654: "",
          radio80337: "",
          input113152: "",
          input40240: "",
          radio48252: "",
          input78584: "",
          input32153: "",
          input82694: "",
          radio15322: "",
          select30151: "",
          radio7296: "",
          date23034: null,
          date101014: null,
          date36546: null,
          date65368: null,
          date35169: null,
          radio37785: null,
          select66842: "",
          fileupload21603: null,
          fileupload21116: null,
          fileupload64222: null,
          fileupload95845: null,
          fileupload93148: null,
          fileupload45459: null,
          fileupload97014: null,
          fileupload95564: null,
          fileupload8438: null,
          fileupload59826: null,
          input50733: "",
          fileupload59469: null,
        },
        rules: {
          input12931: [{
            required: true,
            message: 'Must Fill In',
          }],
          input69350: [{
            required: true,
            message: 'Must Fill In',
          }],
          input23031: [{
            required: true,
            message: 'Must Fill In',
          }],
          input96155: [{
            required: true,
            message: 'Must Fill In',
          }, {
            pattern: /^([-_A-Za-z0-9.]+)@([_A-Za-z0-9]+\.)+[A-Za-z0-9]{2,3}$/,
            trigger: ['blur', 'change'],
            message: ''
          }],
          textarea21654: [{
            required: true,
            message: 'Must Fill In',
          }],
          textarea105654: [{
            required: true,
            message: 'Must Fill In',
          }],
          radio80337: [{
            required: true,
            message: 'Must Fill In',
          }],
          input113152: [{
            required: true,
            message: 'Must Fill In',
          }],
          input40240: [{
            required: true,
            message: 'Must Fill In',
          }],
          radio48252: [{
            required: true,
            message: 'Must Fill In',
          }],
          input78584: [{
            required: true,
            message: 'Must Fill In',
          }],
          input32153: [{
            required: true,
            message: 'Must Fill In',
          }],
          input82694: [{
            required: true,
            message: 'Must Fill In',
          }],
          select30151: [{
            required: true,
            message: 'Must Fill In',
          }],
          radio7296: [{
            required: true,
            message: 'Must Fill In',
          }],
          date23034: [{
            required: true,
            message: 'Must Fill In',
          }],
          date101014: [{
            required: true,
            message: 'Must Fill In',
          }],
          date36546: [{
            required: true,
            message: 'Must Fill In',
          }],
          date65368: [{
            required: true,
            message: 'Must Fill In',
          }],
          date35169: [{
            required: true,
            message: 'Must Fill In',
          }],
          radio37785: [{
            required: true,
            message: 'Must Fill In',
          }],
          select66842: [{
            required: true,
            message: 'Must Fill In',
          }],
          fileupload21116: [{
            required: false,
            message: 'Must Fill In',
          }],
        },
        radio80337Options: [{
          "label": "Bachelor",
          "value": "1"
        }, {
          "label": "Master",
          "value": "2"
        }, {
          "label": "Doctor of philosophy",
          "value": "3"
        }],
        radio48252Options: [{
          "label": "Inside Malaysia",
          "value": "1"
        }, {
          "label": "Outside Malaysia",
          "value": "2"
        }],
        radio15322Options: [{
          "label": "Self Finance",
          "value": "1"
        }, {
          "label": "Sponsorship",
          "value": "2"
        }],
        select30151Options: [{
          "label": "CONTINUE/ PROBATION",
          "value": "1"
        }, {
          "label": "THESIS SUBMITTED",
          "value": "2"
        }, {
          "label": "DROPPED",
          "value": "3"
        }, {
          "value": "4",
          "label": "DEFER"
        }, {
          "value": "5",
          "label": "COMPLETED"
        }, {
          "value": "6",
          "label": "TERMINATED"
        }],
        radio7296Options: [{
          "label": "Single",
          "value": "1"
        }, {
          "label": "Married",
          "value": "2"
        }, {
          "label": "Divorced",
          "value": "3"
        }],
        radio37785Options: [{
          "label": "INTERNATIONAL PASSPORT",
          "value": 1
        }, {
          "label": "DIPLOMATIC PASSPORT",
          "value": 2
        }],
        select66842Options: [{
          "label": "STUDENT PASS",
          "value": "1"
        }, {
          "label": "SOCIAL PASS",
          "value": "2"
        }, {
          "label": "FIRST SPECIAL PASS",
          "value": "3"
        }, {
          "value": "4",
          "label": "SECOND SPECIAL PASS"
        }],
        fileupload21603FileList: [],
        fileupload21603UploadHeaders: {},
        fileupload21603UploadData: {},
        fileupload21116FileList: [],
        fileupload21116UploadHeaders: {},
        fileupload21116UploadData: {},
        fileupload64222FileList: [],
        fileupload64222UploadHeaders: {},
        fileupload64222UploadData: {},
        fileupload95845FileList: [],
        fileupload95845UploadHeaders: {},
        fileupload95845UploadData: {},
        fileupload93148FileList: [],
        fileupload93148UploadHeaders: {},
        fileupload93148UploadData: {},
        fileupload45459FileList: [],
        fileupload45459UploadHeaders: {},
        fileupload45459UploadData: {},
        fileupload97014FileList: [],
        fileupload97014UploadHeaders: {},
        fileupload97014UploadData: {},
        fileupload95564FileList: [],
        fileupload95564UploadHeaders: {},
        fileupload95564UploadData: {},
        fileupload8438FileList: [],
        fileupload8438UploadHeaders: {},
        fileupload8438UploadData: {},
        fileupload59826FileList: [],
        fileupload59826UploadHeaders: {},
        fileupload59826UploadData: {},
        fileupload59469FileList: [],
        fileupload59469UploadHeaders: {},
        fileupload59469UploadData: {},
      })

      const instance = getCurrentInstance();

      // 针对boarding Pass文件上传成功的处理函数
      const onboardingPassUploadSuccess = (response, file, fileList) => {
        // 假设后端返回的文件路径在response.data.filePath中
        state.formData.boardingPassFilePath = response.data.filePath;
        // 更新文件列表显示（可选，根据实际需求）
        state.fileupload21603FileList = fileList;
      };

      // 针对Passport文件上传成功的处理函数
      const onPassportUploadSuccess = (response, file, fileList) => {
        state.formData.passportFilePath = response.data.filePath;
        state.fileupload21116FileList = fileList;
      };

      // 针对Old Passport文件上传成功的处理函数（如果有）
      const onOldPassportUploadSuccess = (response, file, fileList) => {
        state.formData.oldPassportFilePath = response.data.filePath;
        state.fileupload64222FileList = fileList;
      };

      const submitForm = () => {
        console.log('submitForm函数被触发');
        instance.proxy.$refs['vForm'].validate(valid => {
          if (!valid) return;
          const formData = new FormData();
          for (const key in state.formData) {
            if (state.formData.hasOwnProperty(key) && key!== 'fileupload21603FileList' && key!== 'fileupload21116FileList' && key!== 'fileupload64222FileList') {
              formData.append(key, state.formData[key]);
            }
          }
          axios.post('http://localhost:8080/apply/submitFormData', formData, {
            headers: {
              'Content-Type':'multipart/form-data'
            }
          })
              .then(response => {
                console.log('提交成功', response);
                ElMessageBox.alert('Submit Successful', 'Notification', {
                  confirmButtonText: 'Continue'
                });
              })
              .catch(error => {
                console.error('提交失败', error);
                ElMessageBox.alert('提交失败：' + error.message, '错误', {
                  confirmButtonText: '确定'
                });
              });
        });
      };

      const resetForm = () => {
        instance.proxy.$refs['vForm'].resetFields();
      };

      return {
        // 解构响应式数据和方法，使其在模板中可直接使用
        ...toRefs(state),
        submitForm,
        resetForm,
        onboardingPassUploadSuccess,
        onPassportUploadSuccess,
        onOldPassportUploadSuccess
      };
    }
  })

</script>

<style lang="scss">
  .el-input-number.full-width-input,
  .el-cascader.full-width-input {
    width: 100% !important;
  }
  
  .el-form-item--medium {
    .el-radio {
      line-height: 36px !important;
    }
    
    .el-rate {
      margin-top: 8px;
    }
  }
  
  .el-form-item--small {
    .el-radio {
      line-height: 32px !important;
    }
    
    .el-rate {
      margin-top: 6px;
    }
  }
  
  .el-form-item--mini {
    .el-radio {
      line-height: 28px !important;
    }
    
    .el-rate {
      margin-top: 4px;
    }
  }
  
  .clear-fix:before,
  .clear-fix:after {
    display: table;
    content: "";
  }
  
  .clear-fix:after {
    clear: both;
  }
  
  .float-right {
    float: right;
  }
  
  /* 表单整体右移 20px */
  form {
    margin-left: 20px;
  }
  
  /* 所有标签内容居中 */
  form label {
    display: block;
    text-align: center;
  }
  
</style>

<style lang="scss" scoped>
  div.table-container {
    table.table-layout {
      width: 100%;
      table-layout: fixed;
      border-collapse: collapse;

      td.table-cell {
        display: table-cell;
        height: 36px;
        border: 1px solid #e1e2e3;
      }
    }
  }
  
  div.tab-container {}
  
  .label-left-align :deep(.el-form-item__label) {
    text-align: left;
  }
  
  .label-center-align :deep(.el-form-item__label) {
    text-align: center;
  }
  
  .label-right-align :deep(.el-form-item__label) {
    text-align: right;
  }
  
  .custom-label {}
  
  .static-content-item {
    min-height: 20px;
    display: flex;
    align-items: center;

    :deep(.el-divider--horizontal) {
      margin: 0;
    }
  }
  


</style>